# Homebrew formula for studyctl
# Install: brew install NetDevAutomate/studyctl/studyctl
# Tap:     brew tap NetDevAutomate/studyctl
#
# This formula is for a personal tap (not homebrew-core).
# Resource stanzas can be auto-generated with:
#   brew update-python-resources Formula/studyctl.rb

class Studyctl < Formula
  include Language::Python::Virtualenv

  desc "AuDHD-aware study tool with AI Socratic mentoring and spaced repetition"
  homepage "https://github.com/NetDevAutomate/socratic-study-mentor"
  url "https://files.pythonhosted.org/packages/source/s/studyctl/studyctl-2.1.0.tar.gz"
  sha256 "PLACEHOLDER_SHA256_UPDATE_AFTER_PYPI_PUBLISH"
  license "MIT"

  depends_on "python@3.12"

  # Resource stanzas generated by: brew update-python-resources Formula/studyctl.rb
  # Core deps: click, rich, pyyaml
  # Run `brew update-python-resources` after publishing to PyPI to populate these.

  def install
    virtualenv_install_with_resources
  end

  def caveats
    <<~EOS
      studyctl is installed! Get started:
        studyctl setup

      Optional system dependencies for full functionality:
        brew install pandoc          # Obsidian markdown to PDF conversion
        npm install -g @mermaid-js/mermaid-cli  # Mermaid diagram rendering

      Optional Python extras:
        uv pip install 'studyctl[web]'        # FastAPI web UI
        uv pip install 'studyctl[tui]'        # Terminal dashboard
        uv pip install 'studyctl[content]'    # PDF splitting (pymupdf)
        uv pip install 'studyctl[mcp]'        # MCP agent integration
        uv pip install 'studyctl[notebooklm]' # NotebookLM API
        uv pip install 'studyctl[all]'        # Everything

      MCP server for AI assistants:
        claude mcp add studyctl-mcp
    EOS
  end

  test do
    assert_match "studyctl", shell_output("#{bin}/studyctl --version")
    assert_match "Usage:", shell_output("#{bin}/studyctl --help")
  end
end
