# Homebrew formula for studyctl
# Install: brew install NetDevAutomate/studyctl/studyctl
# Tap:     brew tap NetDevAutomate/studyctl
#
# This formula is for a personal tap (not homebrew-core).
# Resource stanzas can be auto-generated with:
#   brew update-python-resources Formula/studyctl.rb

class Studyctl < Formula
  include Language::Python::Virtualenv

  desc "AuDHD-aware study tool with AI Socratic mentoring and spaced repetition"
  homepage "https://github.com/NetDevAutomate/socratic-study-mentor"
  url "https://files.pythonhosted.org/packages/source/s/studyctl/studyctl-2.3.0.tar.gz"
  sha256 "2f0084ed5457a307cba112c40b08ec9b9b18c64aae500eec7ab9c3127ed1459f"  # pragma: allowlist secret
  license "MIT"

  depends_on "python@3.12"

  # Resource stanzas generated by: brew update-python-resources Formula/studyctl.rb
  # Core deps: click, rich, pyyaml
  # Run `brew update-python-resources` after publishing to PyPI to populate these.

  resource "click" do
    url "https://files.pythonhosted.org/packages/3d/fa/656b739db8587d7b5dfa22e22ed02566950fbfbcdc20311993483657a5c0/click-8.3.1.tar.gz"
    sha256 "12ff4785d337a1bb490bb7e9c2b1ee5da3112e94a8622f26a6c77f5d2fc6842a"
  end

  resource "markdown-it-py" do
    url "https://files.pythonhosted.org/packages/5b/f5/4ec618ed16cc4f8fb3b701563655a69816155e79e24a17b651541804721d/markdown_it_py-4.0.0.tar.gz"
    sha256 "cb0a2b4aa34f932c007117b194e945bd74e0ec24133ceb5bac59009cda1cb9f3"
  end

  resource "mdurl" do
    url "https://files.pythonhosted.org/packages/d6/54/cfe61301667036ec958cb99bd3efefba235e65cdeb9c84d24a8293ba1d90/mdurl-0.1.2.tar.gz"
    sha256 "bb413d29f5eea38f31dd4754dd7377d4465116fb207585f97bf925588687c1ba"
  end

  resource "pygments" do
    url "https://files.pythonhosted.org/packages/b0/77/a5b8c569bf593b0140bde72ea885a803b82086995367bf2037de0159d924/pygments-2.19.2.tar.gz"
    sha256 "636cb2477cec7f8952536970bc533bc43743542f70392ae026374600add5b887"
  end

  resource "pyyaml" do
    url "https://files.pythonhosted.org/packages/05/8e/961c0007c59b8dd7729d542c61a4d537767a59645b82a0b521206e1e25c2/pyyaml-6.0.3.tar.gz"
    sha256 "d76623373421df22fb4cf8817020cbb7ef15c725b9d5e45f17e189bfc384190f"
  end

  resource "rich" do
    url "https://files.pythonhosted.org/packages/b3/c6/f3b320c27991c46f43ee9d856302c70dc2d0fb2dba4842ff739d5f46b393/rich-14.3.3.tar.gz"
    sha256 "b8daa0b9e4eef54dd8cf7c86c03713f53241884e814f4e2f5fb342fe520f639b"
  end

  def install
    virtualenv_install_with_resources
  end

  def caveats
    <<~EOS
      studyctl is installed! Get started:
        studyctl setup

      Optional system dependencies for full functionality:
        brew install pandoc          # Obsidian markdown to PDF conversion
        npm install -g @mermaid-js/mermaid-cli  # Mermaid diagram rendering

      Optional Python extras:
        uv pip install 'studyctl[web]'        # FastAPI web UI
        uv pip install 'studyctl[tui]'        # Terminal dashboard
        uv pip install 'studyctl[content]'    # PDF splitting (pymupdf)
        uv pip install 'studyctl[mcp]'        # MCP agent integration
        uv pip install 'studyctl[notebooklm]' # NotebookLM API
        uv pip install 'studyctl[all]'        # Everything

      MCP server for AI assistants:
        claude mcp add studyctl-mcp
    EOS
  end

  test do
    assert_match "studyctl", shell_output("#{bin}/studyctl --version")
    assert_match "Usage:", shell_output("#{bin}/studyctl --help")
  end
end
