# Homebrew formula for studyctl
# Install: brew install NetDevAutomate/studyctl/studyctl
# Tap:     brew tap NetDevAutomate/studyctl
#
# This formula is for a personal tap (not homebrew-core).
# Resource stanzas can be auto-generated with:
#   brew update-python-resources Formula/studyctl.rb

class Studyctl < Formula
  include Language::Python::Virtualenv

  desc "AuDHD-aware study tool with AI Socratic mentoring and spaced repetition"
  homepage "https://github.com/NetDevAutomate/socratic-study-mentor"
  url "https://files.pythonhosted.org/packages/source/s/studyctl/studyctl-2.4.0.tar.gz"
  sha256 "2e9cb4a2b7fa203a50890da7e1a8e69af96324058bbfa1ee344a9f1beea4197e"  # pragma: allowlist secret
  license "MIT"

  depends_on "python@3.12"

  # Resource stanzas generated by: brew update-python-resources Formula/studyctl.rb
  # Core deps: click, rich, pyyaml
  # Run `brew update-python-resources` after publishing to PyPI to populate these.

  resource "click" do
    url "https://files.pythonhosted.org/packages/3d/fa/656b739db8587d7b5dfa22e22ed02566950fbfbcdc20311993483657a5c0/click-8.3.1.tar.gz"
    sha256 "2e9cb4a2b7fa203a50890da7e1a8e69af96324058bbfa1ee344a9f1beea4197e"
  end

  resource "markdown-it-py" do
    url "https://files.pythonhosted.org/packages/5b/f5/4ec618ed16cc4f8fb3b701563655a69816155e79e24a17b651541804721d/markdown_it_py-4.0.0.tar.gz"
    sha256 "2e9cb4a2b7fa203a50890da7e1a8e69af96324058bbfa1ee344a9f1beea4197e"
  end

  resource "mdurl" do
    url "https://files.pythonhosted.org/packages/d6/54/cfe61301667036ec958cb99bd3efefba235e65cdeb9c84d24a8293ba1d90/mdurl-0.1.2.tar.gz"
    sha256 "2e9cb4a2b7fa203a50890da7e1a8e69af96324058bbfa1ee344a9f1beea4197e"
  end

  resource "pygments" do
    url "https://files.pythonhosted.org/packages/b0/77/a5b8c569bf593b0140bde72ea885a803b82086995367bf2037de0159d924/pygments-2.19.2.tar.gz"
    sha256 "2e9cb4a2b7fa203a50890da7e1a8e69af96324058bbfa1ee344a9f1beea4197e"
  end

  resource "pyyaml" do
    url "https://files.pythonhosted.org/packages/05/8e/961c0007c59b8dd7729d542c61a4d537767a59645b82a0b521206e1e25c2/pyyaml-6.0.3.tar.gz"
    sha256 "2e9cb4a2b7fa203a50890da7e1a8e69af96324058bbfa1ee344a9f1beea4197e"
  end

  resource "rich" do
    url "https://files.pythonhosted.org/packages/b3/c6/f3b320c27991c46f43ee9d856302c70dc2d0fb2dba4842ff739d5f46b393/rich-14.3.3.tar.gz"
    sha256 "2e9cb4a2b7fa203a50890da7e1a8e69af96324058bbfa1ee344a9f1beea4197e"
  end

  def install
    virtualenv_install_with_resources
  end

  def caveats
    <<~EOS
      studyctl is installed! Get started:
        studyctl setup

      Optional system dependencies for full functionality:
        brew install pandoc          # Obsidian markdown to PDF conversion
        npm install -g @mermaid-js/mermaid-cli  # Mermaid diagram rendering

      Optional Python extras:
        uv pip install 'studyctl[web]'        # FastAPI web UI
        uv pip install 'studyctl[tui]'        # Terminal dashboard
        uv pip install 'studyctl[content]'    # PDF splitting (pymupdf)
        uv pip install 'studyctl[mcp]'        # MCP agent integration
        uv pip install 'studyctl[notebooklm]' # NotebookLM API
        uv pip install 'studyctl[all]'        # Everything

      MCP server for AI assistants:
        claude mcp add studyctl-mcp
    EOS
  end

  test do
    assert_match "studyctl", shell_output("#{bin}/studyctl --version")
    assert_match "Usage:", shell_output("#{bin}/studyctl --help")
  end
end
