"""Self-contained flashcard and quiz JSON loader.

Reads the same JSON format generated by pdf-by-chapters from-obsidian.
No cross-package imports — the JSON format is the contract.

Flashcard format: {"title": "...", "cards": [{"front": "...", "back": "..."}]}
Quiz format: {"title": "...", "questions": [{"question": "...", "answerOptions": [...]}]}
"""

from __future__ import annotations

import hashlib
import json
import random
from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class Flashcard:
    front: str
    back: str
    source: str = ""

    @property
    def card_hash(self) -> str:
        """Stable hash for spaced repetition tracking."""
        return hashlib.sha256(self.front.encode()).hexdigest()[:16]


@dataclass
class QuizOption:
    text: str
    is_correct: bool
    rationale: str = ""


@dataclass
class QuizQuestion:
    question: str
    options: list[QuizOption]
    hint: str = ""
    source: str = ""

    @property
    def card_hash(self) -> str:
        """Stable hash for spaced repetition tracking."""
        return hashlib.sha256(self.question.encode()).hexdigest()[:16]


@dataclass
class ReviewResult:
    total: int = 0
    correct: int = 0
    incorrect: int = 0
    skipped: int = 0
    wrong_hashes: list[str] = field(default_factory=list)

    @property
    def score_pct(self) -> float:
        attempted = self.correct + self.incorrect
        return (self.correct / attempted * 100) if attempted > 0 else 0.0


def load_flashcards(directory: Path) -> list[Flashcard]:
    """Load all flashcard JSON files from a directory."""
    cards: list[Flashcard] = []
    for path in sorted(directory.glob("*flashcards.json")):
        try:
            data = json.loads(path.read_text())
            source = data.get("title", path.stem)
            for card in data.get("cards", []):
                cards.append(Flashcard(front=card["front"], back=card["back"], source=source))
        except (json.JSONDecodeError, KeyError):
            continue
    return cards


def load_quizzes(directory: Path) -> list[QuizQuestion]:
    """Load all quiz JSON files from a directory."""
    questions: list[QuizQuestion] = []
    for path in sorted(directory.glob("*quiz.json")):
        try:
            data = json.loads(path.read_text())
            source = data.get("title", path.stem)
            for q in data.get("questions", []):
                options = [
                    QuizOption(
                        text=opt["text"],
                        is_correct=opt.get("isCorrect", False),
                        rationale=opt.get("rationale", ""),
                    )
                    for opt in q.get("answerOptions", [])
                ]
                questions.append(
                    QuizQuestion(
                        question=q["question"],
                        options=options,
                        hint=q.get("hint", ""),
                        source=source,
                    )
                )
        except (json.JSONDecodeError, KeyError):
            continue
    return questions


def discover_directories(config_dirs: list[str] | None = None) -> list[tuple[str, Path]]:
    """Discover course directories with flashcard/quiz content.

    Returns list of (course_name, directory_path) tuples.
    Searches configured directories and their subdirectories.
    """
    if not config_dirs:
        return []

    courses: list[tuple[str, Path]] = []
    for dir_str in config_dirs:
        base = Path(dir_str).expanduser()
        if not base.is_dir():
            continue

        # Check if this directory itself has content
        if _has_review_content(base):
            courses.append((base.name, base))
            continue

        # Check subdirectories (e.g. downloads/flashcards/)
        downloads = base / "downloads"
        if downloads.is_dir() and _has_review_content(downloads):
            courses.append((base.name, downloads))
            continue

        # Check immediate children
        for child in sorted(base.iterdir()):
            if child.is_dir() and _has_review_content(child):
                courses.append((child.name, child))

    return courses


def _has_review_content(directory: Path) -> bool:
    """Check if a directory has flashcard or quiz JSON files."""
    fc_dir = directory / "flashcards"
    quiz_dir = directory / "quizzes"

    if fc_dir.is_dir() and list(fc_dir.glob("*flashcards.json")):
        return True
    if quiz_dir.is_dir() and list(quiz_dir.glob("*quiz.json")):
        return True
    if list(directory.glob("*flashcards.json")):
        return True
    return bool(list(directory.glob("*quiz.json")))


def find_content_dirs(directory: Path) -> tuple[Path | None, Path | None]:
    """Find flashcard and quiz subdirectories within a directory."""
    fc_dir: Path | None = None
    quiz_dir: Path | None = None

    fc_sub = directory / "flashcards"
    if fc_sub.is_dir() and list(fc_sub.glob("*-flashcards.json")):
        fc_dir = fc_sub
    elif list(directory.glob("*flashcards.json")):
        fc_dir = directory

    quiz_sub = directory / "quizzes"
    if quiz_sub.is_dir() and list(quiz_sub.glob("*-quiz.json")):
        quiz_dir = quiz_sub
    elif list(directory.glob("*quiz.json")):
        quiz_dir = directory

    return fc_dir, quiz_dir


def shuffle_items(items: list, enabled: bool = True) -> list:
    """Shuffle a list if enabled."""
    if enabled:
        result = list(items)
        random.shuffle(result)
        return result
    return items
