#!/usr/bin/env python3
"""Set up GitHub Pages artefact player for a repo.

Drops a standard index.html into docs/artefacts/ and updates README.md
links to point at the GitHub Pages player.

Standard artefact filenames (place in docs/artefacts/):
  audio_overview.m4a   video_overview.mp4
  infographic.png      slides.pdf

Usage:
  python scripts/setup_artefacts_page.py                          # auto-detect from git remote
  python scripts/setup_artefacts_page.py --org NetDevAutomate --repo My-Repo
"""
from __future__ import annotations

import argparse
import re
import shutil
import subprocess
from pathlib import Path

TEMPLATE = Path(__file__).resolve().parent.parent / "docs" / "artefacts" / "index.html"

README_BLOCK = """\
<!-- ARTEFACTS:START -->
## Generated Artefacts

- 🎧 Audio Overview: [audio_overview.m4a](https://{org_lower}.github.io/{repo}/artefacts/)
- 🖼️ Infographic: [infographic.png](https://{org_lower}.github.io/{repo}/artefacts/#infographic)
- 📊 Slide Deck: [slides.pdf](https://{org_lower}.github.io/{repo}/artefacts/#slides)
- 🎬 Video Overview: [video_overview.mp4](https://{org_lower}.github.io/{repo}/artefacts/#video)

*Generated by [notebooklm-repo-artefacts](https://github.com/andytaylor/notebooklm-repo-artefacts) via Google NotebookLM.*
<!-- ARTEFACTS:END -->"""


def get_github_info(repo_root: Path) -> tuple[str, str]:
    """Extract org/repo from git remote."""
    out = subprocess.check_output(
        ["git", "remote", "-v"], cwd=repo_root, text=True
    )
    for line in out.splitlines():
        m = re.search(r"github\.com[:/]([^/]+)/([^/\s]+?)(?:\.git)?(?:\s|$)", line)
        if m:
            return m.group(1), m.group(2)
    raise SystemExit("No GitHub remote found. Use --org and --repo.")


def setup(repo_root: Path, org: str, repo: str) -> None:
    artefacts_dir = repo_root / "docs" / "artefacts"
    artefacts_dir.mkdir(parents=True, exist_ok=True)

    # Copy template (use this repo's index.html as the canonical template)
    dest = artefacts_dir / "index.html"
    if TEMPLATE.exists() and TEMPLATE != dest:
        shutil.copy2(TEMPLATE, dest)
        print(f"  Copied player template → {dest.relative_to(repo_root)}")
    elif not dest.exists():
        raise SystemExit(f"No template found at {TEMPLATE}")

    # Update title in the HTML
    html = dest.read_text()
    html = re.sub(r"<title>.*?</title>", f"<title>Artefacts — {repo}</title>", html)
    dest.write_text(html)

    # Update README
    readme = repo_root / "README.md"
    if not readme.exists():
        print("  No README.md found, skipping link update")
        return

    text = readme.read_text()
    block = README_BLOCK.format(org_lower=org.lower(), repo=repo)

    if "<!-- ARTEFACTS:START -->" in text:
        text = re.sub(
            r"<!-- ARTEFACTS:START -->.*?<!-- ARTEFACTS:END -->",
            block, text, flags=re.DOTALL,
        )
        print("  Updated existing artefacts block in README.md")
    else:
        text = text.rstrip() + "\n\n" + block + "\n"
        print("  Appended artefacts block to README.md")

    readme.write_text(text)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, default=Path.cwd())
    parser.add_argument("--org", help="GitHub org/user")
    parser.add_argument("--repo", help="GitHub repo name")
    args = parser.parse_args()

    root = args.repo_root.resolve()
    org = args.org
    repo = args.repo
    if not org or not repo:
        org, repo = get_github_info(root)

    print(f"Setting up artefacts page for {org}/{repo}")
    setup(root, org, repo)
    print(f"\nDone! Enable GitHub Pages (Settings → Pages → source: main, folder: /docs)")
    print(f"Player will be at: https://{org.lower()}.github.io/{repo}/artefacts/")


if __name__ == "__main__":
    main()
